version: '3'
services:
    app:
      build: ./
      ports:
        - "8080:8080"
        - "5000:5000"
      volumes:
        - ./src:/src
      environment:
        - LC_ALL=C.UTF-8
        - LANG=C.UTF-8