version: '3'
services:
    app:
      build: ./
      image: audeldiaz/flask-vue-spa
      ports:
        - "5000:5000"
      volumes:
        - ./src:/src
      environment:
        - LC_ALL=C.UTF-8
        - LANG=C.UTF-8